### ISSUE TITLE
Context "list" not works properly

### ISSUE THREAD

**Issue by jpol-xumak** [DantaFramework/JahiaDF#15]
The last release 080917 the context "list" not works properly, actually we use this feature to create the Main Navigation component.

The following lines has the configuration for the xk-config-json file

{
        "xk_componentCategory": [
            "list",
            "traversedList",
            "pageDetails",
            "getInternalExternalLink",
            "jsonFormatProcess"
        ],
        "xk_pathRefKeyName": "global.rootPath",
        "depth": "2",
        "xk_depthKeyName": "config.depth",
        "xk_extraListPropertyNames": [
        "hideInNav",
        "subtitle"
        ],
        "linkInternalExternalProperties": [
            "global.socialLinkList"
        ],
        "jsonFormatProperties": [
            "list.pages",
            "global.socialLinkList"
        ]
    }

**Comment by josecarlosgt** [comment]
Is it that the list context doesn't appear in the template or why it doesn't work?

**Comment by jpol-xumak** [comment]
After doing more testing it doesn't works the "list" context because the configuration in xk-config-json file it use the property **"xk_pathRefKeyName": "global.rootPath"** but the configuration added to this property not is showed in the global context. only the children nodes properties  under global is showed  eg;  **mainList**, **secondaryList** ... but not the properties settled in the global node as rootPath, logoPath etc.

JCR Structure 
```
-content
   - layerx
      -global    ( the properties for this node not is showed in the global context.)
         -mainList
         -secondaryList     
``` 
    
So in this case the list context not works because depends a value configured in  **"global.rootPath"**

**Comment by josecarlosgt** [comment]
OK. Thanks for the clarification! I think the CP that adds the global properties is overriding the whole context. I am looking into that.

**Comment by josecarlosgt** [comment]
I found another issue with the lists context which seems to happen only in the Danta version. Are we supporting bug fixes for both versions LayerX and Danta?

**Comment by jpol-xumak** [comment]
I think that the changes should be in both, what do yo think about ?

**Comment by josecarlosgt** [comment]
OK. I understand. I will do the fix in both versions and deal with the problem of the lists context in Danta in a different issue.

**Comment by jbarrera-xumak** [comment]
I don’t think is necessary do the fix for LayerX too, because no projects will use that version.

**Comment by josecarlosgt** [comment]
OK

**Comment by josecarlosgt** [comment]
I have tried a fresh install of Jahia and I am still getting the problem with the lists CPs not resolving the workspace correctly. Again, this only happens in Danta version.

**Comment by josecarlosgt** [comment]
#16 fixes this issue. The fix was made to the CP handling the global context, so any CP using paths from the global context to populate traversed lists should work now.

**Comment by jbarrera-xumak** [comment]
Pull request #16 to fix the issue this issue was merged.
To have lists working properly it is pending to solve this other issue #17

**Comment by dpolanco-xumak** [comment]
@jpol-xumak this issue has been solved you can test it
