### ISSUE TITLE
Lists context not working anymore

### ISSUE THREAD

**Issue by josecarlosgt** [DantaFramework/JahiaDF#17]
The lists CPs seem to stop working, at least in my instance. The method for converting weakreferences to URLs is not recognizing the workspace (edit, live) anymore so that the URLs generated by the traversed and curated CPs are just empty strings. The problem it is not in the lists CPs themselves, but in this method:

- ResourceUtils.getResourceNodePath

which is used to translate weakreferences (resource IDs) to URLs. In edit mode, this method returns the URLs as if they were browsed from a page in live mode.

This is very weird because it works perfectly in LayerX version and the code looks the same. I am not sure if this is happening only in my instance or if it is a bug that resulted from the migration to Danta.

**Comment by jbarrera-xumak** [comment]
Same issue in my local environment.

**Comment by josecarlosgt** [comment]
OK. I will work on this.

**Comment by josecarlosgt** [comment]
Fix added in #22

**Comment by dpolanco-xumak** [comment]
@jbarrera-xumak @neozilon @josecarlosgt  was this resolved? I understand there was a PR pending for this one
